# -*- coding: utf-8 -*-
"""Task 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QGOXJU1LE-JpscZY62XKfR3yAcXGOWz0
"""

def fibonacci(n, first=0, second=1):
    # Validate the input
    if not isinstance(n, int) or n < 0:
        raise ValueError("Input must be a non-negative integer.")

    # Use a generator to yield Fibonacci numbers
    def fib_generator():
        a, b = first, second
        for _ in range(n):
            yield a
            a, b = b, a + b

    return list(fib_generator())

# Example usage: Generate the first 10 terms of the Fibonacci series
n = 10
fib_series = fibonacci(n)
print(f"Fibonacci series up to {n} terms: {fib_series}")

